version: "0.0.1"

services:
  backend: 
    depends_on: 
      - mongo
    build: ./backend
    ports: 
      - 5001:5001
    environment: 
      DB_URL: mongodb://mongo/samfree
    command: ./docker-entrypoint.sh

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - diskspace:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    ports:
      - 8081:8081

volumes:
  diskspace: