version: "0.0.1"

services:
  backend: 
    depends_on: 
      - mongo
    build: ./backend
    ports: 
      - 5001:5001
    environment: 
      DB_URL: mongodb://db/samfree
    command: ./docker-entrypoint.sh

  mongo:
    image: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
        - MONGO_INITDB_DATABASE=samfree
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - samfree:/data/db

  mongo-workbench:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - 8081:8081

volumes:
  samfree: